#Build the Arduino Eclipse Plugin using Maven

node:
#Make quiet to reduce logs (Travis will kill if 4MB log exceeded)
#But not too quiet - we break apart the build (Travis will kill after 10 mins of no output)
#we also need to keep it under 75 mins
script:
  #This is testing (I am not sure if travis encrypted vars are available in pull requests)
  - sh -c "if $TRAVIS_SECURE_ENV_VARS; then echo TRAVIS SECURE AVAILABLE; else echo TRAVIS SECURE NOT AVAIALABLE; fi"
  #- mvn deploy -Pall,juno --quiet --settings settings.xml
  - sh -c "if $TRAVIS_SECURE_ENV_VARS; then mvn deploy -Pall,juno --quiet --settings settings.xml; else mvn verify -Pall,juno --quiet --settings settings.xml; fi"
  #- mvn deploy -Pall,kepler --quiet --settings settings.xml
  - sh -c "if $TRAVIS_SECURE_ENV_VARS; then mvn deploy -Pall,kepler --quiet --settings settings.xml; else mvn verify -Pall,kepler --quiet --settings settings.xml; fi"
  #- mvn deploy -Pall,luna --quiet --settings settings.xml
  - sh -c "if $TRAVIS_SECURE_ENV_VARS; then mvn deploy -Pall,luna --quiet --settings settings.xml; else mvn verify -Pall,luna --quiet --settings settings.xml; fi"
  

#Several usernames and passwords/tokens are required for deployment.
#When testing on your local/remote setup then you need to set/export env. variables:
#(See settings.xml)
#CI_NEXUS_USERNAME
#CI_NEXUS_OAUTH2_TOKEN
#CI_GPG_PASSPHRASE
#CI_GITHUB_REPOUSERNAME
env:
  global:
    #Make sure Maven doesn't run out of heap memory.
    - MAVEN_OPTS="-Xmx1024M"

    #These are the Nexus details and GPG signing token for Nexus deployment.
    #The Nexus repo is hardcoded as com.github.brodykenrick.arduino-eclipse-plugin in the POM.XML (doing otherwise produces warnings)
    #This is good to use until we want more consistency in naming
    #Travis encrypted variables names and tokens (need to change for correct repo though for encryption to work).
    #Nexus Username, pass and GPG
    # These point to the above nexus server/groupid but need to be encrypted against the repo Travis is getting code from (i.e. change it).
    #brodykenrick/arduino-eclipse-plugin
#    - secure: "CkTScsFgbeqTznfGoAhhS0XRie2jr+syjpD3Vvn8Gw/OFCXkKjDEBWUebQdpJjXe9ia23dmTdQMFwp2HcPhrUj6cpnHNcOqVSfPRKfYPbYgXMmVSciGfqkgY3aWArddQ1G8SOMzivfYW6QZIkhanFsk00HkWOrYzxppXyA3m4GY="
#    - secure: "bd0gCncNkyhwmIHkir2d7jprS+HNTd4DOVutYpIKQTVaJpvFKRw4anqZGMZp3wwxPyP3i30fMVvPoFJVCEphxRuJRomeqgrJJUpKAsh5QAIODYj9A2A8/KDa+jrTtbpPh16YAiMPmnMgq4NT3Wd5cjZuuBHxRmvaMMlb6BoJCO0="
#    - secure: "oFSaKCjBm8L8ZgSvC3rAPKIXcXXJuEb+3eQ+lJbU84QK6C7wRd+2mz4fQ0E5GNSNxWACPbtypopUCPj4auCazhcbudO2wzpAksfJJpkIXd6vZN6xmxJLRzQWp7aNQG7a0UWvuY49/11IY834uhxPoJHBIFRh9jALHMLeF4epfko="
    #jantje/arduino-eclipse-plugin
    - secure: "kC8R35qKesohed2C47R2xO4uVKhRGahuO+7kEDaJwWIn7QlefJSgJ8IK9tGng+IcUUXD4ClKAT1RJgJnnchtO0jpUEy+MIXDQi1PCc2UkIsYa6XMw5Nf0EMppHiJM2LLbf1n/urGmuo/RwKWXLdC7SLuSmqgLD82AbrGA2xXSXM="
    - secure: "gUpJ6dlh/SBsJP+QlNFbNhchZzKRDmwuWjrId7lTyToVhAzoQSygNS7DfuemfJkhIdHVkZELnvfTx3FaeIfW59zQ2654HMiUrvUINFys+pq6C0vwPyQzAXg4KLn6kExgbn6md5zb8w2fE68Mb2y20jduhzBOAVWvK361lC4oeSI="
    - secure: "ZNF1Tc17sq5tsChKi4+yAv6mqhxOfq/zZ38TnRYr1zos2G1jCJJNw4zq1ojUGFViCxdt76xwlDYwavjzAMfsdI3/zoPePtaFJj3w8V6y4C10rgGW67bY4HwW2i0sudIbSWQ+skmG2zbVvJLrIMj2c6IXDM13sTW1Dv+Pt4tTaSs="

    # This is the Github username of the repository of the source we are building.
    #Needs to be inline with the repo being built (i.e. change it).
    - CI_GITHUB_REPOUSERNAME=jantje
#    - CI_GITHUB_REPOUSERNAME=brodykenrick





